import { NextRequest, NextResponse } from 'next/server';
import { requireClient } from '@/lib/session';
import { sendEmail, reportEmail } from '@/lib/email';
import { prisma } from '@/lib/prisma';

export async function POST(request: NextRequest) {
  const result = await requireClient();
  if ('error' in result) return result.error;
  const { clientId, user } = result;

  const body = await request.json();
  const { to, reportType, reportTitle } = body;

  if (!to || !reportType) {
    return NextResponse.json({ error: 'to and reportType required' }, { status: 400 });
  }

  const client = await prisma.client.findUnique({ where: { id: clientId }, select: { name: true } });
  const baseUrl = process.env.NEXTAUTH_URL || 'https://volt-spark.vercel.app';

  const email = reportEmail({
    recipientName: to.split('@')[0],
    reportTitle: reportTitle || 'Compliance Report',
    companyName: client?.name || 'Company',
    reportUrl: `${baseUrl}/reports`,
    highlights: [
      `Report type: ${reportTitle || reportType}`,
      `Generated by: ${user.name}`,
      `Date: ${new Date().toLocaleDateString()}`,
      'Login to VoltSpark to view the full report with data.',
    ],
  });

  const sent = await sendEmail({ to, ...email });

  return NextResponse.json({ ok: sent });
}
