'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, Cpu, ShieldCheck } from 'lucide-react';
import PageHeader from '@/components/layout/PageHeader';
import StatusBadge from '@/components/ui/StatusBadge';
import { EmptyState } from '@/components/ui/EmptyState';
import { formatDate } from '@/lib/utils';

interface Incident {
  id: string;
  type: string;
  severity: string;
  title: string;
  description: string;
  location: string | null;
  incidentDate: string;
  status: string;
  autoGenerated: boolean;
  source: string | null;
  reportedBy: { name: string } | null;
  meterAlert: { type: string; meter: { name: string; model: string | null } | null } | null;
  frameworkRequirement: { code: string; title: string; framework: { code: string; name: string } } | null;
}

const SEVERITY_COLORS: Record<string, 'gray' | 'blue' | 'yellow' | 'orange' | 'red' | 'green' | 'purple'> = {
  NEAR_MISS: 'yellow',
  MINOR: 'orange',
  MAJOR: 'red',
  FATAL: 'red',
};

const STATUS_COLORS: Record<string, 'gray' | 'blue' | 'yellow' | 'orange' | 'red' | 'green' | 'purple'> = {
  OPEN: 'red',
  INVESTIGATING: 'yellow',
  CORRECTIVE_ACTION: 'blue',
  CLOSED: 'green',
};

export default function IncidentsPage() {
  const router = useRouter();
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'ALL' | 'AUTO' | 'MANUAL' | 'OPEN'>('ALL');

  useEffect(() => {
    fetch('/api/incidents')
      .then((r) => r.json())
      .then(setIncidents)
      .finally(() => setLoading(false));
  }, []);

  const filtered = incidents.filter((i) => {
    if (filter === 'AUTO') return i.autoGenerated;
    if (filter === 'MANUAL') return !i.autoGenerated;
    if (filter === 'OPEN') return i.status !== 'CLOSED';
    return true;
  });

  const autoCount = incidents.filter((i) => i.autoGenerated).length;
  const openCount = incidents.filter((i) => i.status !== 'CLOSED').length;

  if (loading) return <div className="animate-pulse space-y-4"><div className="h-8 bg-gray-200 rounded w-48" /><div className="h-96 bg-gray-200 rounded-lg" /></div>;

  return (
    <div className="space-y-6">
      <PageHeader title="Incidents" subtitle="Safety and compliance events — manual reports plus auto-generated from meter breaches" />

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <button onClick={() => setFilter('ALL')} className={`card text-left ${filter === 'ALL' ? 'ring-2 ring-brand-500' : ''}`}>
          <p className="text-2xl font-bold">{incidents.length}</p>
          <p className="text-xs text-gray-500">Total</p>
        </button>
        <button onClick={() => setFilter('OPEN')} className={`card text-left ${filter === 'OPEN' ? 'ring-2 ring-brand-500' : ''}`}>
          <p className="text-2xl font-bold text-red-600">{openCount}</p>
          <p className="text-xs text-gray-500">Open</p>
        </button>
        <button onClick={() => setFilter('AUTO')} className={`card text-left ${filter === 'AUTO' ? 'ring-2 ring-brand-500' : ''}`}>
          <p className="text-2xl font-bold text-purple-600">{autoCount}</p>
          <p className="text-xs text-gray-500">Auto-generated</p>
        </button>
        <button onClick={() => setFilter('MANUAL')} className={`card text-left ${filter === 'MANUAL' ? 'ring-2 ring-brand-500' : ''}`}>
          <p className="text-2xl font-bold">{incidents.length - autoCount}</p>
          <p className="text-xs text-gray-500">Manual reports</p>
        </button>
      </div>

      {filtered.length === 0 ? (
        <EmptyState
          icon={ShieldCheck}
          title="No incidents"
          description={filter === 'AUTO' ? 'No meter or sensor breaches have escalated to incidents.' : 'No incidents to show in this view.'}
        />
      ) : (
        <div className="card overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="text-xs text-gray-500 border-b">
              <tr>
                <th className="text-left py-2 px-3 font-medium">Date</th>
                <th className="text-left py-2 px-3 font-medium">Title</th>
                <th className="text-left py-2 px-3 font-medium">Source</th>
                <th className="text-left py-2 px-3 font-medium">Severity</th>
                <th className="text-left py-2 px-3 font-medium">Compliance</th>
                <th className="text-left py-2 px-3 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filtered.map((i) => (
                <tr key={i.id} onClick={() => router.push(`/safety/incidents/${i.id}`)} className="hover:bg-gray-50 cursor-pointer">
                  <td className="py-3 px-3 whitespace-nowrap text-gray-600">{formatDate(i.incidentDate)}</td>
                  <td className="py-3 px-3">
                    <p className="font-medium">{i.title}</p>
                    {i.location && <p className="text-xs text-gray-500">{i.location}</p>}
                  </td>
                  <td className="py-3 px-3">
                    {i.autoGenerated ? (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-purple-50 text-purple-700 text-xs font-medium">
                        <Cpu className="h-3 w-3" />
                        {i.meterAlert?.meter?.name ?? 'Auto'}
                      </span>
                    ) : (
                      <span className="text-xs text-gray-500">{i.reportedBy?.name ?? 'Manual'}</span>
                    )}
                  </td>
                  <td className="py-3 px-3"><StatusBadge label={i.severity} color={SEVERITY_COLORS[i.severity] ?? 'gray'} /></td>
                  <td className="py-3 px-3">
                    {i.frameworkRequirement ? (
                      <div>
                        <p className="text-xs font-medium">{i.frameworkRequirement.framework.code}</p>
                        <p className="text-xs text-gray-500">{i.frameworkRequirement.code}</p>
                      </div>
                    ) : (
                      <span className="text-xs text-gray-400">—</span>
                    )}
                  </td>
                  <td className="py-3 px-3"><StatusBadge label={i.status.replace('_', ' ')} color={STATUS_COLORS[i.status] ?? 'gray'} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {autoCount > 0 && (
        <div className="card bg-purple-50 border-purple-200">
          <div className="flex items-start gap-3">
            <AlertTriangle className="h-5 w-5 text-purple-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-purple-900">Auto-generated incidents close the compliance loop</p>
              <p className="text-purple-700 mt-1">
                When a meter reading breaches a configured threshold (demand, power factor, voltage, THD), VoltSpark automatically creates an
                incident and links it to the relevant compliance framework requirement. No manual entry needed — the evidence trail builds itself.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
