import { prisma } from '@/lib/prisma';

// Map MeterAlert.type → Incident type + severity + title + framework-requirement evidence module hint
// Why: each electrical alert corresponds to a different compliance/safety concern.
const ALERT_TO_INCIDENT: Record<
  string,
  { type: string; severity: string; titlePrefix: string; evidenceModule: string }
> = {
  DEMAND_BREACH: {
    type: 'ELECTRICAL',
    severity: 'MAJOR',
    titlePrefix: 'Demand breach',
    evidenceModule: 'CONSUMPTION',
  },
  DEMAND_CRITICAL: {
    type: 'ELECTRICAL',
    severity: 'MAJOR',
    titlePrefix: 'Demand critical',
    evidenceModule: 'CONSUMPTION',
  },
  PF_LOW: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'Low power factor',
    evidenceModule: 'CONSUMPTION',
  },
  VOLTAGE_SAG: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'Voltage sag',
    evidenceModule: 'INSPECTION',
  },
  VOLTAGE_SWELL: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'Voltage swell',
    evidenceModule: 'INSPECTION',
  },
  THD_HIGH: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'High THD',
    evidenceModule: 'INSPECTION',
  },
};

interface AlertInput {
  id: string;
  clientId: string;
  meterId: string | null;
  type: string;
  message: string;
}

interface MeterInfo {
  name: string;
  location: string | null;
}

/**
 * Promote a MeterAlert into an Incident when it represents a compliance concern.
 *
 * Dedup: one open auto-incident per meter+type in any 24-hour window — prevents
 * the incidents feed from flooding when a sensor keeps breaching its threshold.
 *
 * Framework linkage: best-effort lookup against the client's active frameworks
 * to tag a relevant requirement (CONSUMPTION/INSPECTION etc.) for traceability.
 */
export async function maybeCreateAutoIncident(
  alert: AlertInput,
  meter: MeterInfo | null
): Promise<void> {
  const mapping = ALERT_TO_INCIDENT[alert.type];
  if (!mapping) return;

  // 24-hour dedup window keyed on meter + type
  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const recent = await prisma.incident.findFirst({
    where: {
      clientId: alert.clientId,
      meterAlert: { meterId: alert.meterId, type: alert.type },
      autoGenerated: true,
      createdAt: { gte: dayAgo },
    },
  });
  if (recent) return;

  // Best-effort framework requirement tag — find the first active framework requirement
  // whose evidenceModule matches this alert type.
  const reqMatch = await prisma.frameworkRequirement.findFirst({
    where: {
      evidenceModule: mapping.evidenceModule,
      framework: { clientFrameworks: { some: { clientId: alert.clientId, status: 'ACTIVE' } } },
    },
    select: { id: true },
  });

  await prisma.incident.create({
    data: {
      clientId: alert.clientId,
      type: mapping.type,
      severity: mapping.severity,
      title: meter ? `${mapping.titlePrefix} on ${meter.name}` : mapping.titlePrefix,
      description: alert.message,
      location: meter?.location ?? undefined,
      incidentDate: new Date(),
      status: 'OPEN',
      autoGenerated: true,
      source: 'METER_ALERT',
      meterAlertId: alert.id,
      frameworkRequirementId: reqMatch?.id,
    },
  });
}
