import { prisma } from '@/lib/prisma';
import { generateCAPANumber } from '@/lib/utils';

// Incident severities that should automatically spawn a CAPA — these need root cause
// analysis and corrective/preventive action, not just acknowledgement.
const CAPA_SEVERITIES = new Set(['MAJOR', 'FATAL']);

// CAPA priority follows incident severity. FATAL is rare for energy events but keep
// the mapping symmetric so the rule applies uniformly to future sensor incidents.
const SEVERITY_TO_PRIORITY: Record<string, string> = {
  MAJOR: 'HIGH',
  FATAL: 'CRITICAL',
};

// Sensor type → which incident bucket it belongs to. Temp/humidity in cold storage
// and OT/ICU rooms are typically CHEMICAL/SAFETY events; vibration and pressure
// fall into MECHANICAL. Frameworks like HACCP, NABH, and ISO 50001 all reference
// these — use INSPECTION as the evidence module since sensors are the
// continuous-monitoring equivalent of periodic inspections.
const SENSOR_TYPE_TO_INCIDENT: Record<string, { type: string; titleParameter: string }> = {
  TEMPERATURE: { type: 'OTHER', titleParameter: 'Temperature' },
  HUMIDITY: { type: 'OTHER', titleParameter: 'Humidity' },
  CO2: { type: 'CHEMICAL', titleParameter: 'CO₂' },
  AIR_QUALITY: { type: 'CHEMICAL', titleParameter: 'Air quality' },
  VIBRATION: { type: 'MECHANICAL', titleParameter: 'Vibration' },
  PRESSURE: { type: 'MECHANICAL', titleParameter: 'Pressure' },
  OTHER: { type: 'OTHER', titleParameter: 'Sensor reading' },
};

// Map MeterAlert.type → Incident type + severity + title + framework-requirement evidence module hint
// Why: each electrical alert corresponds to a different compliance/safety concern.
const ALERT_TO_INCIDENT: Record<
  string,
  { type: string; severity: string; titlePrefix: string; evidenceModule: string }
> = {
  DEMAND_BREACH: {
    type: 'ELECTRICAL',
    severity: 'MAJOR',
    titlePrefix: 'Demand breach',
    evidenceModule: 'CONSUMPTION',
  },
  DEMAND_CRITICAL: {
    type: 'ELECTRICAL',
    severity: 'MAJOR',
    titlePrefix: 'Demand critical',
    evidenceModule: 'CONSUMPTION',
  },
  PF_LOW: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'Low power factor',
    evidenceModule: 'CONSUMPTION',
  },
  VOLTAGE_SAG: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'Voltage sag',
    evidenceModule: 'INSPECTION',
  },
  VOLTAGE_SWELL: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'Voltage swell',
    evidenceModule: 'INSPECTION',
  },
  THD_HIGH: {
    type: 'ELECTRICAL',
    severity: 'MINOR',
    titlePrefix: 'High THD',
    evidenceModule: 'INSPECTION',
  },
};

interface AlertInput {
  id: string;
  clientId: string;
  meterId: string | null;
  type: string;
  message: string;
}

interface MeterInfo {
  name: string;
  location: string | null;
}

/**
 * Promote a MeterAlert into an Incident when it represents a compliance concern.
 *
 * Dedup: one open auto-incident per meter+type in any 24-hour window — prevents
 * the incidents feed from flooding when a sensor keeps breaching its threshold.
 *
 * Framework linkage: best-effort lookup against the client's active frameworks
 * to tag a relevant requirement (CONSUMPTION/INSPECTION etc.) for traceability.
 */
export async function maybeCreateAutoIncident(
  alert: AlertInput,
  meter: MeterInfo | null
): Promise<void> {
  const mapping = ALERT_TO_INCIDENT[alert.type];
  if (!mapping) return;

  // 24-hour dedup window keyed on meter + type
  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const recent = await prisma.incident.findFirst({
    where: {
      clientId: alert.clientId,
      meterAlert: { meterId: alert.meterId, type: alert.type },
      autoGenerated: true,
      createdAt: { gte: dayAgo },
    },
  });
  if (recent) return;

  // Best-effort framework requirement tag — find the first active framework requirement
  // whose evidenceModule matches this alert type.
  const reqMatch = await prisma.frameworkRequirement.findFirst({
    where: {
      evidenceModule: mapping.evidenceModule,
      framework: { clientFrameworks: { some: { clientId: alert.clientId, status: 'ACTIVE' } } },
    },
    select: { id: true },
  });

  const incident = await prisma.incident.create({
    data: {
      clientId: alert.clientId,
      type: mapping.type,
      severity: mapping.severity,
      title: meter ? `${mapping.titlePrefix} on ${meter.name}` : mapping.titlePrefix,
      description: alert.message,
      location: meter?.location ?? undefined,
      incidentDate: new Date(),
      status: 'OPEN',
      autoGenerated: true,
      source: 'METER_ALERT',
      meterAlertId: alert.id,
      frameworkRequirementId: reqMatch?.id,
    },
  });

  // For high-severity incidents, also spawn a CAPA. CAPAs require RCA + action plan
  // closure, so this is what actually drives the consultant to investigate root cause.
  if (CAPA_SEVERITIES.has(mapping.severity)) {
    await spawnAutoCAPA(alert.clientId, incident.id, incident.title, alert.message, mapping.severity, reqMatch?.id);
  }
}

interface SensorAlertInput {
  id: string;
  clientId: string;
  sensorId: string;
  type: string; // SENSOR_LOW | SENSOR_HIGH
  severity: string; // WARNING | CRITICAL
  message: string;
}

interface SensorInfo {
  id: string;
  name: string;
  sensorType: string;
  unit: string;
  location: string | null;
  assetName: string | null;
}

/**
 * Sensor counterpart to maybeCreateAutoIncident — same shape, same dedup window,
 * but maps the alert via sensor type (vs alert type for meters) since the
 * sensor universe is broader and the compliance bucket depends on what's being
 * measured, not just whether a threshold was crossed.
 */
export async function maybeCreateAutoIncidentFromSensor(
  alert: SensorAlertInput,
  sensor: SensorInfo
): Promise<void> {
  const mapping = SENSOR_TYPE_TO_INCIDENT[sensor.sensorType] ?? SENSOR_TYPE_TO_INCIDENT.OTHER;
  const incidentSeverity = alert.severity === 'CRITICAL' ? 'MAJOR' : 'MINOR';

  // Dedup by sensor + alert type within 24h
  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const recent = await prisma.incident.findFirst({
    where: {
      clientId: alert.clientId,
      sensorId: alert.sensorId,
      autoGenerated: true,
      createdAt: { gte: dayAgo },
      meterAlert: { type: alert.type },
    },
  });
  if (recent) return;

  // INSPECTION is the natural framework module for sensor-driven evidence —
  // sensors continuously verify what an inspection would check periodically.
  const reqMatch = await prisma.frameworkRequirement.findFirst({
    where: {
      evidenceModule: 'INSPECTION',
      framework: { clientFrameworks: { some: { clientId: alert.clientId, status: 'ACTIVE' } } },
    },
    select: { id: true },
  });

  const titlePrefix = alert.type === 'SENSOR_LOW' ? `Low ${mapping.titleParameter}` : `High ${mapping.titleParameter}`;
  const assetLabel = sensor.assetName ? ` on ${sensor.assetName}` : ` on ${sensor.name}`;

  const incident = await prisma.incident.create({
    data: {
      clientId: alert.clientId,
      type: mapping.type,
      severity: incidentSeverity,
      title: titlePrefix + assetLabel,
      description: alert.message,
      location: sensor.location ?? undefined,
      incidentDate: new Date(),
      status: 'OPEN',
      autoGenerated: true,
      source: 'SENSOR_BREACH',
      meterAlertId: alert.id,
      sensorId: alert.sensorId,
      frameworkRequirementId: reqMatch?.id,
    },
  });

  if (CAPA_SEVERITIES.has(incidentSeverity)) {
    await spawnAutoCAPA(alert.clientId, incident.id, incident.title, alert.message, incidentSeverity, reqMatch?.id);
  }
}

// Shared CAPA-from-incident creation. Extracted so meter and sensor paths share
// identical defaults (7-day due date, priority mapping, source=INCIDENT).
async function spawnAutoCAPA(
  clientId: string,
  incidentId: string,
  title: string,
  description: string,
  severity: string,
  frameworkRequirementId: string | undefined
): Promise<void> {
  const capaCount = await prisma.cAPA.count({ where: { clientId } });
  await prisma.cAPA.create({
    data: {
      clientId,
      capaNumber: generateCAPANumber(capaCount),
      type: 'CORRECTIVE',
      source: 'INCIDENT',
      sourceReference: incidentId,
      title,
      description,
      priority: SEVERITY_TO_PRIORITY[severity] ?? 'HIGH',
      status: 'OPEN',
      autoGenerated: true,
      incidentId,
      frameworkRequirementId,
      actionDueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    },
  });
}
