'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Cpu, ShieldCheck, AlertTriangle, ExternalLink } from 'lucide-react';
import PageHeader from '@/components/layout/PageHeader';
import StatusBadge from '@/components/ui/StatusBadge';
import { formatDate } from '@/lib/utils';

interface Incident {
  id: string;
  type: string;
  severity: string;
  title: string;
  description: string;
  location: string | null;
  incidentDate: string;
  status: string;
  immediateAction: string | null;
  rootCause: string | null;
  correctiveAction: string | null;
  preventiveAction: string | null;
  followUpDate: string | null;
  closedDate: string | null;
  autoGenerated: boolean;
  source: string | null;
  reportedBy: { name: string; email: string } | null;
  closedBy: { name: string; email: string } | null;
  meterAlert: {
    id: string;
    type: string;
    severity: string;
    parameterName: string | null;
    actualValue: number | null;
    thresholdValue: number | null;
    message: string;
    createdAt: string;
    meter: { id: string; name: string; model: string | null; location: string | null } | null;
  } | null;
  frameworkRequirement: { code: string; title: string; framework: { code: string; name: string } } | null;
}

const SEVERITY_COLORS: Record<string, string> = { NEAR_MISS: 'yellow', MINOR: 'orange', MAJOR: 'red', FATAL: 'red' };
const STATUS_COLORS: Record<string, string> = { OPEN: 'red', INVESTIGATING: 'yellow', CORRECTIVE_ACTION: 'blue', CLOSED: 'green' };
const STATUS_FLOW = ['OPEN', 'INVESTIGATING', 'CORRECTIVE_ACTION', 'CLOSED'];

export default function IncidentDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = params.id as string;

  const [incident, setIncident] = useState<Incident | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [rootCause, setRootCause] = useState('');
  const [correctiveAction, setCorrectiveAction] = useState('');
  const [preventiveAction, setPreventiveAction] = useState('');
  const [immediateAction, setImmediateAction] = useState('');

  useEffect(() => {
    fetch(`/api/incidents/${id}`)
      .then(r => (r.ok ? r.json() : null))
      .then((data: Incident | null) => {
        if (data) {
          setIncident(data);
          setRootCause(data.rootCause ?? '');
          setCorrectiveAction(data.correctiveAction ?? '');
          setPreventiveAction(data.preventiveAction ?? '');
          setImmediateAction(data.immediateAction ?? '');
        }
      })
      .finally(() => setLoading(false));
  }, [id]);

  const patch = async (data: Record<string, unknown>) => {
    setSaving(true);
    const res = await fetch(`/api/incidents/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (res.ok) {
      const updated = await fetch(`/api/incidents/${id}`).then(r => r.json());
      setIncident(updated);
    }
    setSaving(false);
  };

  const advanceStatus = () => {
    if (!incident) return;
    const idx = STATUS_FLOW.indexOf(incident.status);
    const next = STATUS_FLOW[Math.min(idx + 1, STATUS_FLOW.length - 1)];
    patch({ status: next });
  };

  const saveActions = () => patch({ rootCause, correctiveAction, preventiveAction, immediateAction });

  if (loading) return <div className="animate-pulse space-y-4"><div className="h-8 bg-gray-200 rounded w-48" /><div className="h-96 bg-gray-200 rounded-lg" /></div>;
  if (!incident) return <div className="text-red-600">Incident not found. <Link href="/safety/incidents" className="underline">Back to list</Link></div>;

  const nextStatusIdx = STATUS_FLOW.indexOf(incident.status) + 1;
  const nextStatus = nextStatusIdx < STATUS_FLOW.length ? STATUS_FLOW[nextStatusIdx] : null;

  return (
    <div className="space-y-6">
      <button onClick={() => router.push('/safety/incidents')} className="text-sm text-gray-600 hover:text-gray-900 flex items-center gap-1">
        <ArrowLeft className="h-4 w-4" /> Back to incidents
      </button>

      <PageHeader
        title={incident.title}
        subtitle={`${incident.type} · ${formatDate(incident.incidentDate)}${incident.location ? ' · ' + incident.location : ''}`}
        action={
          nextStatus && incident.status !== 'CLOSED' ? (
            <button onClick={advanceStatus} disabled={saving} className="btn-primary text-sm">
              {saving ? 'Saving…' : `Move to ${nextStatus.replace('_', ' ')}`}
            </button>
          ) : undefined
        }
      />

      <div className="flex flex-wrap gap-2">
        <StatusBadge label={incident.severity} color={SEVERITY_COLORS[incident.severity] ?? 'gray'} />
        <StatusBadge label={incident.status.replace('_', ' ')} color={STATUS_COLORS[incident.status] ?? 'gray'} />
        {incident.autoGenerated && (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
            <Cpu className="h-3 w-3" /> Auto-generated from meter
          </span>
        )}
      </div>

      {incident.autoGenerated && incident.meterAlert && (
        <div className="card bg-purple-50 border-purple-200">
          <div className="flex items-start gap-3">
            <Cpu className="h-5 w-5 text-purple-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1 text-sm space-y-1">
              <p className="font-medium text-purple-900">Source: Meter Alert</p>
              <p className="text-purple-700">
                <span className="font-medium">{incident.meterAlert.meter?.name ?? 'Unknown meter'}</span>
                {incident.meterAlert.meter?.model && <> · {incident.meterAlert.meter.model}</>}
                {incident.meterAlert.meter?.location && <> · {incident.meterAlert.meter.location}</>}
              </p>
              <p className="text-purple-700">{incident.meterAlert.message}</p>
              {incident.meterAlert.parameterName && incident.meterAlert.actualValue !== null && incident.meterAlert.thresholdValue !== null && (
                <p className="text-xs text-purple-600">
                  {incident.meterAlert.parameterName}: actual <strong>{incident.meterAlert.actualValue.toFixed(2)}</strong> vs threshold {incident.meterAlert.thresholdValue.toFixed(2)}
                </p>
              )}
              <p className="text-xs text-purple-600">Triggered {formatDate(incident.meterAlert.createdAt)}</p>
            </div>
          </div>
        </div>
      )}

      {incident.frameworkRequirement && (
        <div className="card bg-blue-50 border-blue-200">
          <div className="flex items-start gap-3">
            <ShieldCheck className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-blue-900">Linked compliance requirement</p>
              <p className="text-blue-700">
                <span className="font-medium">{incident.frameworkRequirement.framework.code}</span> · {incident.frameworkRequirement.code} — {incident.frameworkRequirement.title}
              </p>
              <p className="text-xs text-blue-600 mt-1">Closing this incident strengthens the evidence trail for {incident.frameworkRequirement.framework.name}.</p>
            </div>
          </div>
        </div>
      )}

      <div className="card">
        <h3 className="font-semibold mb-2">Description</h3>
        <p className="text-sm text-gray-700 whitespace-pre-wrap">{incident.description}</p>
      </div>

      <div className="card space-y-4">
        <h3 className="font-semibold flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-orange-500" /> Investigation & Actions</h3>
        <div>
          <label className="label-text">Immediate action taken</label>
          <textarea className="input-field" rows={2} value={immediateAction} onChange={e => setImmediateAction(e.target.value)} placeholder="What was done immediately to contain the issue?" />
        </div>
        <div>
          <label className="label-text">Root cause</label>
          <textarea className="input-field" rows={3} value={rootCause} onChange={e => setRootCause(e.target.value)} placeholder="Why did this happen? (5-Why, fishbone, etc.)" />
        </div>
        <div>
          <label className="label-text">Corrective action</label>
          <textarea className="input-field" rows={2} value={correctiveAction} onChange={e => setCorrectiveAction(e.target.value)} placeholder="What was done to fix the immediate cause?" />
        </div>
        <div>
          <label className="label-text">Preventive action</label>
          <textarea className="input-field" rows={2} value={preventiveAction} onChange={e => setPreventiveAction(e.target.value)} placeholder="What was done to prevent recurrence?" />
        </div>
        <button onClick={saveActions} disabled={saving} className="btn-secondary text-sm">
          {saving ? 'Saving…' : 'Save'}
        </button>
      </div>

      <div className="grid grid-cols-2 gap-3 text-xs text-gray-600">
        <div>
          <p className="text-gray-400">Reported by</p>
          <p>{incident.reportedBy?.name ?? (incident.autoGenerated ? 'System (auto-generated)' : '—')}</p>
        </div>
        <div>
          <p className="text-gray-400">Closed by</p>
          <p>{incident.closedBy?.name ?? '—'}{incident.closedDate && ' · ' + formatDate(incident.closedDate)}</p>
        </div>
      </div>

      {incident.meterAlert?.meter && (
        <Link href={`/iot/meters?highlight=${incident.meterAlert.meter.id}`} className="inline-flex items-center gap-1 text-sm text-brand-600 hover:underline">
          View source meter <ExternalLink className="h-3 w-3" />
        </Link>
      )}
    </div>
  );
}
